stefan-cooper/SpigotUHC

- src/main/java/com/stefancooper/SpigotUHC/Events.java
- src/main/java/com/stefancooper/SpigotUHC/Plugin.java
- src/main/java/com/stefancooper/SpigotUHC/commands/AbstractCommand.java
- src/main/java/com/stefancooper/SpigotUHC/commands/Config.java
- src/main/java/com/stefancooper/SpigotUHC/resources/ConfigKey.java
- src/main/java/com/stefancooper/SpigotUHC/types/Configurable.java
- refactor and set up the starts to a pattern for how we will add commands in the plugin
> refactor: refactor command code

- src/main/java/com/stefancooper/SpigotUHC/Config.java
- src/main/java/com/stefancooper/SpigotUHC/ConfigParser.java
- src/main/java/com/stefancooper/SpigotUHC/Defaults.java
- src/main/java/com/stefancooper/SpigotUHC/Plugin.java
- src/main/java/com/stefancooper/SpigotUHC/resources/ConfigKey.java
> feat: add default config and default game rules

- .github/workflows/test.yml
- build_plugin.sh
- dependency-reduced-pom.xml
- pom.xml
- src/main/java/com/stefancooper/SpigotUHC/Config.java
- src/main/java/com/stefancooper/SpigotUHC/ConfigParser.java
- src/main/java/com/stefancooper/SpigotUHC/Defaults.java
- src/main/java/com/stefancooper/SpigotUHC/Plugin.java
- src/main/java/com/stefancooper/SpigotUHC/Utils.java
- src/test/java/PluginTest.java
- src/test/java/resources/uhc_config.properties
> feat: add mockbukkit

- .github/workflows/test.yml
- src/main/java/com/stefancooper/SpigotUHC/Config.java
- src/main/java/com/stefancooper/SpigotUHC/ConfigParser.java
- src/main/java/com/stefancooper/SpigotUHC/Defaults.java
- src/main/java/com/stefancooper/SpigotUHC/Plugin.java
- src/main/resources/plugin.yml
- src/test/java/PluginTest.java
- src/test/java/SetConfigTest.java
- src/test/java/ViewConfigTest.java
- src/test/java/resources/uhc_config.properties
> feat: add more tests

- src/main/java/com/stefancooper/SpigotUHC/Defaults.java
- src/main/java/com/stefancooper/SpigotUHC/Events.java
- src/main/java/com/stefancooper/SpigotUHC/Plugin.java
- src/test/java/EventTest.java
- src/test/java/SetConfigTest.java
- src/test/java/ViewConfigTest.java
- src/test/java/resources/uhc_config.properties
Additional remaining defaults created
On death event created
> Added additional defaults and an on death event

- src/main/java/com/stefancooper/SpigotUHC/Config.java
- src/test/java/ViewConfigTest.java
- src/test/java/resources/uhc_config.properties
> feat: sort config before sending it

- src/main/java/com/stefancooper/SpigotUHC/Defaults.java
- src/main/java/com/stefancooper/SpigotUHC/Plugin.java
- src/main/java/com/stefancooper/SpigotUHC/commands/StartCommand.java
- src/test/java/PluginTest.java
- src/test/java/StartTest.java
- src/test/java/resources/uhc_config.properties
> feat: beginning of start command

- pom.xml
- src/main/java/com/stefancooper/SpigotUHC/Config.java
- src/main/java/com/stefancooper/SpigotUHC/ConfigParser.java
- src/main/java/com/stefancooper/SpigotUHC/Defaults.java
- src/main/java/com/stefancooper/SpigotUHC/resources/ConfigKey.java
- src/main/java/com/stefancooper/SpigotUHC/resources/UHCTeam.java
- src/test/java/EventTest.java
- src/test/java/PluginTest.java
- src/test/java/SetConfigTest.java
- src/test/java/StartTest.java
- src/test/java/ViewConfigTest.java
- src/test/java/resources/uhc_config.properties
> feat: register teams

- src/main/java/com/stefancooper/SpigotUHC/Config.java
- src/main/java/com/stefancooper/SpigotUHC/commands/StartCommand.java
- src/main/java/com/stefancooper/SpigotUHC/resources/ConfigKey.java
- src/test/java/SetConfigTest.java
- src/test/java/StartTest.java
> feat: add timers for start command

- src/main/java/com/stefancooper/SpigotUHC/ConfigParser.java
- src/main/java/com/stefancooper/SpigotUHC/Events.java
- src/main/java/com/stefancooper/SpigotUHC/Utils.java
- src/main/java/com/stefancooper/SpigotUHC/commands/StartCommand.java
- src/main/java/com/stefancooper/SpigotUHC/resources/ConfigKey.java
- src/test/java/StartTest.java
- src/test/java/resources/uhc_config.properties
> feat: tweak start commands

- src/main/java/com/stefancooper/SpigotUHC/Events.java
- src/test/java/EventTest.java
Added an event for on respawn which respawns the player at their death location when their gamemode is set to spectate.
> Added a event for On Respawn

- src/main/java/com/stefancooper/SpigotUHC/ConfigParser.java
- src/main/java/com/stefancooper/SpigotUHC/Defaults.java
- src/main/java/com/stefancooper/SpigotUHC/commands/StartCommand.java
- src/main/java/com/stefancooper/SpigotUHC/resources/ConfigKey.java
- src/test/java/StartTest.java
- src/test/java/ViewConfigTest.java
Signed-off-by: Stefan Cooper <Stefan.cooper27@gmail.com>
> feat: add configurable difficulty

- README.md
- pom.xml
- src/main/java/com/stefancooper/SpigotUHC/ConfigParser.java
- src/main/java/com/stefancooper/SpigotUHC/resources/ConfigKey.java
- src/test/java/SetConfigTest.java
> feat: add pink team config

- .gitignore
- src/main/java/com/stefancooper/SpigotUHC/Config.java
- src/main/java/com/stefancooper/SpigotUHC/ConfigParser.java
- src/main/java/com/stefancooper/SpigotUHC/Events.java
- src/main/java/com/stefancooper/SpigotUHC/Utils.java
- src/main/java/com/stefancooper/SpigotUHC/commands/StartCommand.java
- src/main/java/com/stefancooper/SpigotUHC/resources/ConfigKey.java
- src/main/java/com/stefancooper/SpigotUHC/resources/Constants.java
- src/main/java/com/stefancooper/SpigotUHC/types/ManagedResources.java
- src/test/java/TimestampTest.java
- initial implementation will add a timestamp when start command was run, and on any death
Contributes to #39
> feat: add `enable.timestamps` config

- README.md
- src/main/java/com/stefancooper/SpigotUHC/Plugin.java
- src/main/java/com/stefancooper/SpigotUHC/commands/LateStartCommand.java
- src/main/resources/plugin.yml
- src/test/java/LateStartTest.java
> feat: add latestart command

- pom.xml
- src/main/java/com/stefancooper/SpigotUHC/ConfigParser.java
- src/main/java/com/stefancooper/SpigotUHC/commands/StartCommand.java
- src/test/java/PluginTest.java
- src/test/java/ResumeTest.java
- src/test/java/StartTest.java
- This will allow us to build a spawn base outside the world border.
Contributes to: #45 
> feat: don't start world border damage until grace period is over

- src/main/java/com/stefancooper/SpigotUHC/Config.java
- src/main/java/com/stefancooper/SpigotUHC/ConfigParser.java
- src/main/java/com/stefancooper/SpigotUHC/Defaults.java
- src/main/java/com/stefancooper/SpigotUHC/Events.java
- src/main/java/com/stefancooper/SpigotUHC/Utils.java
- src/main/java/com/stefancooper/SpigotUHC/commands/LateStartCommand.java
- src/main/java/com/stefancooper/SpigotUHC/commands/ResumeCommand.java
- src/main/java/com/stefancooper/SpigotUHC/commands/StartCommand.java
- src/main/java/com/stefancooper/SpigotUHC/resources/ConfigKey.java
- src/main/java/com/stefancooper/SpigotUHC/types/BossBarBorder.java
- src/main/java/com/stefancooper/SpigotUHC/types/Worlds.java
- src/test/java/ResumeTest.java
- src/test/java/StartTest.java
- src/test/java/ViewConfigTest.java
- src/test/java/utils/TestUtils.java
> feat: world border in the nether and the end

- README.md
- pom.xml
- src/main/java/com/stefancooper/SpigotUHC/Plugin.java
- src/main/java/com/stefancooper/SpigotUHC/commands/PvpCommand.java
- src/main/resources/plugin.yml
- src/test/java/PvpCommandTest.java
> feat: add manual pvp command

- src/main/java/com/stefancooper/SpigotUHC/commands/CancelCommand.java
> Announcement added for cancel UHC

- README.md
> doc: update readme to include info about pre-loading chunks

- README.md
- pom.xml
- src/main/java/com/stefancooper/SpigotUHC/ConfigParser.java
- src/main/java/com/stefancooper/SpigotUHC/enums/ConfigKey.java
- src/main/java/com/stefancooper/SpigotUHC/events/BaseEvents.java
- src/main/resources/plugin.yml
- src/test/java/EventTest.java
- src/test/java/WorldSpawnTest.java
> feat: add custom world spawn location when UHC is not active

- README.md
- pom.xml
- src/main/java/com/stefancooper/SpigotUHC/Config.java
- src/main/java/com/stefancooper/SpigotUHC/ConfigParser.java
- src/main/java/com/stefancooper/SpigotUHC/Plugin.java
- src/main/java/com/stefancooper/SpigotUHC/commands/ResumeCommand.java
- src/main/java/com/stefancooper/SpigotUHC/commands/StartCommand.java
- src/main/java/com/stefancooper/SpigotUHC/enums/ConfigKey.java
- src/main/java/com/stefancooper/SpigotUHC/events/UHCLootEvents.java
- src/main/java/com/stefancooper/SpigotUHC/types/UHCLoot.java
- src/main/resources/plugin.yml
- src/test/java/UHCLootTest.java
> feat: add random loot chest

- src/main/java/com/stefancooper/SpigotUHC/commands/StartCommand.java
> feat: wipe achievements on start

- README.md
- pom.xml
- src/main/java/com/stefancooper/SpigotUHC/ConfigParser.java
- src/main/java/com/stefancooper/SpigotUHC/enums/ConfigKey.java
- src/main/java/com/stefancooper/SpigotUHC/events/ReviveEvents.java
- src/main/java/com/stefancooper/SpigotUHC/types/Revive.java
- src/main/java/com/stefancooper/SpigotUHC/types/UHCLoot.java
- src/main/resources/plugin.yml
- src/test/java/ReviveTest.java
> feat: add config to revive with any head

- pom.xml
- src/main/java/com/stefancooper/SpigotUHC/Plugin.java
- src/main/java/com/stefancooper/SpigotUHC/events/WinEvents.java
- src/main/java/com/stefancooper/SpigotUHC/utils/UHCCommandTabCompleter.java
- src/main/java/com/stefancooper/SpigotUHC/utils/Win.java
- src/main/resources/plugin.yml
- src/test/java/WinEventTest.java
> feat: announce winners of UHC & QoL for in-game commands

- pom.xml
- src/main/java/com/stefancooper/SpigotUHC/events/BaseEvents.java
- src/main/java/com/stefancooper/SpigotUHC/events/ReviveEvents.java
- src/main/resources/plugin.yml
> feat: make heads indestructible

- pom.xml
- src/main/java/com/stefancooper/SpigotUHC/events/BaseEvents.java
- src/main/resources/plugin.yml
- src/test/java/EventTest.java
> feat: fire cannon on death during UHC

- .github/workflows/publish.yml
- pom.xml
- publish.sh
- src/main/resources/plugin.yml
> featt: add more details to publish message

- README.md
- pom.xml
- src/main/java/com/stefancooper/SpigotUHC/ConfigParser.java
- src/main/java/com/stefancooper/SpigotUHC/enums/ConfigKey.java
- src/main/java/com/stefancooper/SpigotUHC/events/BaseEvents.java
- src/main/resources/plugin.yml
> feat: add optional config to disable witches

- pom.xml
- src/main/java/com/stefancooper/SpigotUHC/events/BaseEvents.java
- src/main/resources/plugin.yml
> fix: fix world border in boss bar on reconnect

- pom.xml
- src/main/java/com/stefancooper/SpigotUHC/commands/StartCommand.java
- src/main/resources/plugin.yml
- src/test/java/StartTest.java
> feat: enable fall damage on uhc start

- pom.xml
- src/main/java/com/stefancooper/SpigotUHC/ConfigParser.java
- src/main/java/com/stefancooper/SpigotUHC/enums/ConfigKey.java
- src/main/java/com/stefancooper/SpigotUHC/events/BaseEvents.java
- src/main/java/com/stefancooper/SpigotUHC/events/WinEvents.java
- src/main/resources/plugin.yml
- src/test/java/DeathChatTest.java
Contributes to: https://github.com/stefan-cooper/SpigotUHC/issues/40
> feat: add death chat

- README.md
- pom.xml
- src/main/java/com/stefancooper/SpigotUHC/ConfigParser.java
- src/main/java/com/stefancooper/SpigotUHC/Defaults.java
- src/main/java/com/stefancooper/SpigotUHC/commands/StartCommand.java
- src/main/java/com/stefancooper/SpigotUHC/enums/ConfigKey.java
- src/main/java/com/stefancooper/SpigotUHC/utils/Constants.java
- src/main/resources/plugin.yml
- src/test/java/ShrinkYBorderTest.java
- src/test/java/SpreadPlayersTest.java
- src/test/java/StartTest.java
- src/test/java/mocks/servers/DispatchCommandServerMock.java
Contributes to: #105
Signed-off-by: Stefan Cooper <Stefan.cooper27@gmail.com>
> feat: add shrinking y border

- pom.xml
- src/main/java/com/stefancooper/SpigotUHC/commands/LateStartCommand.java
- src/main/java/com/stefancooper/SpigotUHC/commands/StartCommand.java
- src/main/resources/plugin.yml
- src/test/java/CraftablePlayerHeadTest.java
- src/test/java/DeathChatTest.java
- src/test/java/EventTest.java
- src/test/java/LateStartTest.java
- src/test/java/NotchAppleTest.java
- src/test/java/PluginTest.java
- src/test/java/PvpCommandTest.java
- src/test/java/RandomFinalLocationTest.java
- src/test/java/RandomiseTeamsCommandTest.java
- src/test/java/ResumeTest.java
- src/test/java/ReviveTest.java
- src/test/java/SetConfigTest.java
- src/test/java/ShrinkYBorderTest.java
- src/test/java/SpreadPlayersTest.java
- src/test/java/StartTest.java
- src/test/java/TimestampTest.java
- src/test/java/UHCLootTest.java
- src/test/java/ViewConfigTest.java
- src/test/java/WinEventTest.java
- src/test/java/WorldSpawnTest.java
- src/test/java/mocks/servers/DispatchCommandServerMock.java
- src/test/java/mocks/servers/RespawnPlayerServerMock.java
- src/test/java/mocks/types/RespawnPlayerMock.java
> chore: bump MockBukkit to `4.33.5`

- README.md
- pom.xml
- src/main/java/com/stefancooper/SpigotUHC/ConfigParser.java
- src/main/java/com/stefancooper/SpigotUHC/ManagedResources.java
- src/main/java/com/stefancooper/SpigotUHC/enums/ConfigKey.java
- src/main/java/com/stefancooper/SpigotUHC/types/UHCLoot.java
- src/main/java/com/stefancooper/SpigotUHC/utils/Utils.java
- src/main/resources/plugin.yml
- src/test/java/UHCLootTest.java
> feat: add config for dynamic loot chest

- README.md
- pom.xml
- src/main/java/com/stefancooper/SpigotUHC/Config.java
- src/main/java/com/stefancooper/SpigotUHC/Plugin.java
- src/main/java/com/stefancooper/SpigotUHC/commands/UnsetConfigCommand.java
- src/main/java/com/stefancooper/SpigotUHC/types/UHCLoot.java
- src/main/java/com/stefancooper/SpigotUHC/utils/UHCCommandTabCompleter.java
- src/main/resources/plugin.yml
- src/test/java/UnsetConfigTest.java
> feat: add unset command

- README.md
- pom.xml
- src/main/java/com/stefancooper/SpigotUHC/commands/CancelCommand.java
- src/main/java/com/stefancooper/SpigotUHC/commands/ResumeCommand.java
- src/main/java/com/stefancooper/SpigotUHC/commands/StartCommand.java
> refactor: fix tech debt

- src/main/java/com/stefancooper/SpigotUHC/events/EnchantmentEvents.java
> fix: fix angled hits on knockback shields

- pom.xml
- src/main/java/com/stefancooper/SpigotUHC/Bootstrap.java
- src/main/java/com/stefancooper/SpigotUHC/ManagedResources.java
- src/main/java/com/stefancooper/SpigotUHC/enchants/EnchantTNT.java
- src/main/java/com/stefancooper/SpigotUHC/enchants/PrepareTNTEnchant.java
- src/main/java/com/stefancooper/SpigotUHC/events/EnchantmentEvents.java
- src/main/java/com/stefancooper/SpigotUHC/utils/Constants.java
- src/main/resources/paper-plugin.yml
- src/main/resources/plugin.yml
> feat: add blastwave enchantment (next)
